# Generated by Django 2.2 on 2020-08-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='initial_tickets',
            field=models.IntegerField(default=0),
        ),
    ]
