# Generated by Django 2.2 on 2020-08-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('O', 'OK'), ('R', 'Redeemed')], default='O', max_length=1, verbose_name='Status'),
        ),
    ]
