version: '3'

services:

  db_prod:
    image: postgres:12.3
    restart: on-failure
    networks:
      - main_prod
    environment:
      POSTGRES_PASSWORD: password
    expose:
      - 5432
  redis_prod:
    image: redis:latest
    networks:
      - main_prod
    expose:
      - 6379
  backend_prod:
    build:
      context: ../../events
      dockerfile: ./docker/backend/Dockerfile
    command: bash -c "sh wait-for-db.sh &&
            python manage.py collectstatic  --no-input &&
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py create_user
              --username admin
              --email admin@admin.com
              --password password
              --no-input &&
            gunicorn -b 0.0.0.0:8001 backend.wsgi"
    restart: on-failure
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.prod
    depends_on:
      - db_prod
      - redis_prod
    networks:
      - main_prod
    expose:
      - 8001
    links:
      - redis_prod
    volumes:
      - ./nginx/staticfiles/:/code/backend/static/

  frontend_prod:
    build:
      context: ../../events
      dockerfile: ./docker/frontend/Dockerfile
    command: bash -c "cd /code && yarn serve"
    networks:
      - main_prod
    expose:
      - 5000
  nginx_prod:
    image: nginx:latest
    networks:
      - main_prod
    ports:
      - "8000:8000"
    links:
      - backend_prod
      - frontend_prod
    depends_on:
      - backend_prod
      - frontend_prod
    volumes:
      - ./nginx/conf.prod:/etc/nginx/conf.d/default.conf
      - ./nginx/staticfiles/:/staticfiles/

networks:
  main_prod: