// Authentication
export const USER_NOT_AUTHENTICATED = "USER_NOT_AUTHENTICATED";
export const USER_IS_AUTHENTICATED = "USER_IS_AUTHENTICATED";

// Loading
export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";

// Notifications
export const PUSH_NOTICICATION = "PUSH_NOTICICATION";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";

// Events
export const EVENTS_REQUESTED = "EVENTS_REQUESTED";
export const EVENTS_LOADED = "EVENTS_LOADED";

// Tickets
export const EVENT_TICKETS_REQUESTED = "EVENT_TICKETS_REQUESTED";
export const EVENT_TICKETS_LOADED = "EVENT_TICKETS";
export const EVENT_TICKETS_REDEEMING_REQUESTED = "EVENT_TICKETS_REDEEMING_REQUESTED";
export const EVENT_TICKET_REDEEMED = "EVENT_TICKET_REDEEMED";
export const NON_REDEEMED_TICKETS_DOWNLOAD_REQUESTED = "NON_REDEEMED_TICKETS_DOWNLOAD_REQUESTED";